-- phpMyAdmin SQL Dump
-- version 4.2.11
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Aug 23, 2017 at 06:04 AM
-- Server version: 5.6.21
-- PHP Version: 5.6.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `library`
--

-- --------------------------------------------------------

--
-- Table structure for table `tblbooks`
--

CREATE TABLE IF NOT EXISTS `tblbooks` (
  `ISBN` varchar(50) NOT NULL,
  `Title` varchar(200) DEFAULT NULL,
  `Author` varchar(50) DEFAULT NULL,
  `Abstract` longtext,
  `Description` varchar(255) DEFAULT NULL,
  `Publisher` varchar(50) DEFAULT NULL,
  `CopyRightYear` varchar(255) DEFAULT NULL,
  `Category` varchar(255) DEFAULT NULL,
  `UnitPrice` decimal(19,4) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tblbooks`
--

INSERT INTO `tblbooks` (`ISBN`, `Title`, `Author`, `Abstract`, `Description`, `Publisher`, `CopyRightYear`, `Category`, `UnitPrice`) VALUES
('0324597681', 'Guide to SQL 8th edition', 'Philip J. Pratt & Mary Z. Last', 'A GUIDE TO SQL, 8E, continues to be the essential SQL reference. It builds on the success of previous editions by presenting basic SQL commands in the context of a running case in which a business uses SQL to manage orders, parts, customers, and sales reps. The book covers the fundamentals of SQL programming using straightforward instruction and extensive hands-on exercises. Continuing with its focus on students learning the basics regardless of the database environment chosen, this edition features examples from the latest databases: Oracle 11g, Access 2007, and MySQL. The eighth edition expands on the use of running case studies by adding a third running case to the extensive hands-on pedagogy at the end of every chapter.', 'Hardbound', 'Course Technology', '2009', 'Databases', '50.0000'),
('0324785151', 'Microsoft Office Access 2007 1st edition', 'Lisa Friedrichsen', 'This Illustrated Introductory Video companion is your personal guide to Microsoft Access 2007. Microsoft Office Access 2007 Illustrated Introductory Video Companion contains over 60 videos, each approximately 5 minutes in length, that map directly to lessons in the Microsoft Office Access 2007 Illustrated Introductory textbook. In addition to the Illustrated Series'' proven two-page spread format in the printed textbook, the videos take viewers step-by-step through each lesson while providing background and explanation for the lesson holistically.', 'Softbound with CD', 'Course Technology', '2009', 'Databases', '35.0000'),
('0534493033', 'Introduction to Wireless and Mobile Systems 2nd edition', 'Dharma P. Agrawal & Qing-An Zeng', 'This text explains the general principles of how wireless systems work, how mobility is supported, what is the underlying infrastructure and what interactions are needed among different functional components. Designed as a textbook appropriate for undergraduate or graduate courses in Computer Science, Electrical Engineering, and Electrical and Computer Engineering, it focuses on qualitative descriptions and the realistic explanations of relationships between wireless systems and performance parameters. Rather than offering a thorough history behind the development of wireless technologies or an exhaustive list of work being carried out, the authors help EE and CSE students learn this exciting technology through relevant examples such as understanding how a cell phone starts working as soon as they get out of an airplane', 'Hardbound without CD', 'Nelson Engineering', '2006', 'Communication', '80.0000'),
('0534525784', 'Introduction to the Internet for Electronic Media 1st edition', 'Daniel Kurland, \r\nFrank (Fritz) Messere', 'no abstract', 'Softbound without CD', 'Wadsworth', '1997', 'Electronic media', '35.0000'),
('0534952852', 'Mechatronics System Design 1st edition', 'Devdas Shetty & Richard Kolk', 'MECHATRONICS - a synergistic combination of mechanical and electrical engineering, computer science, and information technology-is a rapidly emerging technology appropriate for today''s engineering students and practicing engineers. This book combines the core aspects of mechatronics (system modeling, simulation, sensors, actuation, real-time computer interfacing, and control) with practical industrial applications presented in an opitimal way for understanding this new technology. The book features extensive coverage of the modeling and simulation of physical systems (in Chapter 2) made possible by block-diagrams, the modified analogy approach to modeling, and state-of-the-art visual simulation software. A collection of case studies drawn from a variety of industries (complete with parts, lists, setup, and instructions) supports the authors'' applied, design-oriented approach.', 'Hardbound with CD', 'Nelson Engineering', '1998', 'Mechatronics', '78.0000'),
('053495409X', 'Analog and Digital Signal Processing 2e', 'Ashok Ambardar', 'Ambardar''s proven text teaches the basic principles and applications of signals, systems, transforms and filters, using both a visual and mathematical approach. This book helps readers develop a thorough understanding of time-domain and frequency-domain relationships, encouraging them to think clearly in both domains and switch easily from one to the other. Bound into each text is a disk with a set of powerful software routines running under MATLAB® that can be used for reinforcing and visualizing concepts as well as for problem solving and advanced design. The extensively revised and reorganized Second Edition incorporates new practical applications and design-oriented examples in every chapter.', 'Softbound', 'Nelson Engineering', '1999', 'Electronics Engineering', '75.0000'),
('0538688416', 'Microsoft Access 2000: Complete Tutorial 1st edition', 'Sandra Cable, Bill Pasewark', 'Covering beginning through advanced software features, this comprehensive book contains step-by-step instructions, screen illustrations, objectives, tips, notes, chapter summaries, end-of-chapter exercises, projects and SCANS correlations. Certified as Expert level for Access, this book is aimed at beginning through advanced introductory classes.', 'Hardbound with CD', 'Course Technology', '2000', 'Databases', '65.0000'),
('0538688572', 'Microsoft Access 2000 QuickTorial 1st edition', 'Pat Murphy', 'With a completion time of 12+ hours, this book covers beginning through advanced features of the software. Lessons contain objectives, step-by-step instructions, screen illustrations, tips, notes, Internet coverage, chapter summaries, end-of-chapter exercises, projects, and SCANS correlations. Numerous exercises allow the reader to immediately apply what is learned. Integration with other software applications is also covered in the book. It is appropriate for individual or group work.', 'Soft bound with CD', 'Course Technology', '2000', 'Databases', '40.0000'),
('053874393X', 'New Perspectives on Adobe Flash CS3 1st edition', 'Luis A. Lopez,', 'Provides comprehensive coverage of the new Adobe Flash CS3 software. This text uses the New Perspectives real-life case-based, problem-solving approach to teaching this robust software. Students will learn how to create rich interactive experiences for the Web, from banners and interactive menus to a complete Web site with Flash CS3.', 'Softbound', 'Course Technology', '2009', 'Web Design', '50.0000'),
('0538751649', 'Adobe® Flash® CS4 - Illustrated Introductory, International Edition 1st edition', 'Barbara Waxer', 'Teaching your students has never been easier than with ADOBE FLASH CS4 – ILLUSTRATED, International Edition. The book presents each skill on two facing pages, providing detailed instructions on the left-hand page and large, full-color screenshots on the right page. This format helps students intuitively grasp the concepts in the book and apply them to the classroom and workplace environment.\r\nIn addition, the author points out common mistakes and offers "Quick Tips" within the step-by-step directions. Extended case studies and Independent Challenges are available to help students to fully grasp the material. In addition, the text discusses up-to-date features that are new to Adobe Flash CS4, helping to keep students current on technology updates.\r\nADOBE FLASH CS4 – ILLUSTRATED, International Edition is a focused, user-friendly text that offers instructions and succinct lessons to readers. The book includes everything students will need to learn the nuts and bolts of Adobe Flash CS4 and beyond!', 'Softbound without CD', 'Course Technology', '2010', NULL, '45.0000'),
('0619183551', 'Microsoft Office Access 2003: Complete Tutorial 1st edition', 'Pasewark and Pasewark, Sandra Cable', 'Microsoft Office Access 2003 Complete is designed for beginning to intermediate users of Microsoft Office 2003. This self-paced, self-instructional guide provides you with all the instruction necessary to become a Microsoft Office Specialist at the Specialist level for Access.', 'Softbound with CD', 'Course Technology', '2005', 'Databases', '55.0000'),
('0619212845', 'Oracle9i: SQL, with an Introduction to PL/SQL 1st edition', 'Lannes Morris-Murphy', 'Prepares students for the first exam in both the Oracle DBA and Internet Application Developer Certification Tracks, and offers a solid general understanding of Oracle9i SQL.', 'Hardbound without CD', 'Course Technology', '2004', 'Databases', '60.0000'),
('0619216298', 'Guide to Oracle 10g 5th edition', 'Joline Morrison, Mike Morrison & Rocky Conrad', 'Master Oracle''s most recent database with this hands-on, step-by-step approach to teaching Oracle10g and application development tools.', 'Softbound with CD', 'Course Technology', '2006', 'Databases', '65.0000'),
('0619216875', 'PHP Programming with MySQL 1e', 'Don Gosselin', 'As the first true academic textbook in the market to combine PHP with MySQL, PHP Programming with MySQL, by Don Gosselin covers one of the fastest growing technology combinations for developing interactive Web sites.', 'Softbound without CD', 'Course Technology', '2006', 'Databases', '62.0000'),
('0766813916', 'Outdoor Power Equipment (ED Version) 1st edition', 'Jay Webster', 'Designed to assist students in developing the skills required of professionally certified outdoor power equipment technicians, this book features operation, troubleshooting and service information that can be used to maintain and repair commonly used outdoor equipment, including: lawnmowers and garden tractors, snow throwers, leaf blowers and string trimmers, chain saws, and more! Comprehensive in scope, Small Engines for Outdoor Power Equipment begins by acquainting students with shop safety, tools and basic service information. Following exposure to "the big picture" of small engine operation, students are then introduced to the specifics of the ignition system, fuel system, governor and throttle control system, lubrication system, cooling and exhaust system, manual starting system, and the electrical starting and charging system. Both two-stroke and four-stroke engines are covered in detail. Small Engines for Outdoor Power Equipment also features step-by-step photo sequences to illustrate service techniques and provides students with an opportunity to "test" their knowledge by conducting a failure analysis and successfully rebuilding a failed engine.', 'Hardbound with CD', 'Delmar Learning', '2001', 'Automotive', '55.0000'),
('0766838722', 'Electronics for Computer Technology 1st edition', 'David Terrell', 'New from Delmar Learning, Electronics for Computer Technology is perfect for today''s career-minded students as well as anyone with a keen interest in troubleshooting computer devices, components and electrical circuits. The first chapter introduces system-level topics, including representative systems, system notations, functional hierarchies, system connectivity, and system-level troubleshooting. In subsequent chapters, direct references are made to system applications in order to put each topic in the context of an overall system. Some software (programming) topics are addressed, yet emphasis throughout the book is on hardware, including all of the physical parts of the computer plus various electronic components within the computer. Electronic devices are also discussed, along with an overview of digital electronics, computers, and telecommunications. Readers will learn to apply system-level troubleshooting techniques to localize the detailed troubleshooting effort.', 'Softbound with CD', 'Delmar Learning', '2003', 'Electronics', '80.0000'),
('08269-06311', 'Plumbing Design and Installation, Third Edition', 'L.V. Ripka', 'Plumbing Design and Installation, 3rd Edition, contains procedures commonly practiced in industry and the trade. This textbook is designed to develop basic competencies of plumbing apprentices and beginnig learners.', 'Hard bound, Glossy paper and with CD', 'American Technical Publihers, Inc.', '2006', 'Plumbing', '300.0000'),
('0827376995', 'Small Engine Technology (HC) 2nd Edition', 'William Schuster', 'The second edition of this text expands and updates its already thorough coverage of the operation, maintenance and repair of small, air-cooled gas engines. It features new chapters on failure analysis, and starter systems, as well as a rewrite of the electrical chapter to include feedback systems and fuel injection. An expansion of the carburation chapter includes new carburetors including carb 1 carburetors. This text is now accompanied by a comprehensive competency-based workbook.', 'Hardbound without CD', 'Delmar Learning', '1999', 'Automotive', '50.0000'),
('1401840663', 'Game Development Essentials (Video Game Art) 1st edition', 'Todd Gantzler', 'The premiere title in the Game Development Essentials series explores the art of bringing a game designer''s concepts to life. A strong foundation in game artistry is the essential first step, and leading game art designer Todd Gantzler takes readers behind the scenes to show them how to create the entire visual world - from characters to environments - that a game player encounters on the computer screen. Hands-on tutorial instruction suitable for beginning-to-intermediate-level game artists explains the process involved in creating art for real-time 3D digital games and, specifically, video games. The book highlights the technical aspects of preparing art quickly and effectively while conforming to the limitations and specifications of today''s most widely used 3D game engines.', 'Softbound without CD', 'Delmar Learning', '2005', 'Game Art', '65.0000'),
('1401889948', 'Collision Repair And Refinishing', 'Alfred Thomas and Michael Jund', 'This new book covers all the necessary tasks for gaining knowledge of collision repair and refinishing as outlined by NATEF. In-depth coverage includes structural and non-structural analysis and damage repair, welding, painting and refinishing, paint chemistry, sacrificial coatings for corrosion resistance, and more. The logical progression of topics and easy-to-understand style help convey the professional knowledge and technical know-how that readers need to employ on the job.', 'Softbound with CD', 'Published by Delmar Learning', '2010', 'Automotive', '100.0000'),
('1401890075', 'Technician''s Guide to Programmable Controllers 5th edition', 'Richard Cox', 'Hailed as the most comprehensive introduction to PLCs on the market today, this newly updated 5th Edition covers theory, hardware, instructions, programming, installation, startup, and troubleshooting in a way that is easy to understand and apply. New material has been added to explain communication networks, basic control signals, linear scaling of analog process signals, and Proportional Integral Derivative (PID) instructions used by many PLC applications. Supplementary programming examples utilizing the PLC instructions in the book impart a better understanding of the various instructions and how they can be combined to create simple yet effective control logic solutions for today''s world.', 'Softbound without CD', 'Delmar Learning', '2007', 'Programming', '90.0000'),
('1401899188', 'The Guidebook for Linemen and Cablemen 1st edition', 'Wayne Van Soelen', 'A comprehensive and reader-friendly book, The Guidebook for Linemen and Cablemen is a reference tool that contains the most-up-to date information for linemen, cablemen, foremen, and others associated with transmission and distribution departments of electric utility companies. This book discusses the equipment used as well as the responsibilities of a lineman and cablemen. It explains in detail the training and need for safety within this profession. This book is an invaluable resource, providing linemen and cablemen with the best quality and most up-to-date information for their fast growing, technology based, profession.', 'Hardbound', 'Delmar Learning', '2006', 'Utilities', '61.0000'),
('1401899463', 'Internetworking with Cisco and Microsoft Technologies 1st edition', 'Anthony V. Chiarella', 'Learn to use two of the most popular technologies in the industry! This new book teaches how to internetwork with Windows 2000 and Cisco routers. Written in a manner that either the beginner or advanced technician can relate to, the book examines five key areas: network basics, protocols, internetworking, network services and management, and wide area networks. The coverage of networking concepts, makes this an excellent resource and "must have" for any student learning either Cisco routers or Windows 2000.', 'Softbound', 'Delmar Learning', '2004', 'Networking', '68.0000'),
('1418000582', 'Introduction To Local Area Networks 1st edition', 'Judson Miers', 'Readers of this book will learn about Local Area Networks (LAN) through the analysis of case studies that explore common operating systems, network services, security, and more! Each chapter of this innovative book develops a concrete foundation in LAN concepts and applications by exposing readers to a variety of situations and networks. A back-of-book CD-ROM that contains PowerPoint Presentations gives detailed examples of what a business presentation for each case study would look like. Excel spreadsheets are also included so that users can input costs and other data to fashion their own "real world" presentations for a hands-on learning experience.', 'Hardbound', 'Delmar Learning', '2007', 'Networking', '65.0000'),
('1418836354', 'A Guide to MySQL 1st edition', 'Philip J. Pratt & Mary Z. Last', 'A Guide to MySQL, by Philip Pratt and Mary Last, is yet another step into the open-source arena, which is rapidly growing in the technology industry. Topics include design techniques, data definition, commands to query a database, updates, administration and client tools, and finally, MySQL special topics.', 'Softbound', 'Course Technology', '2006', 'Databases', '50.0000'),
('1418837059', 'CCNA Guide to Cisco Networking Fundamentals 4th edition', 'Kelly Cannon, Kelly Caudle, Anthony V. Chiarella', 'CCNA Guide to Cisco Networking Fundamentals, 4e is a comprehensive guide for anyone wishing to obtain a solid background in basic Cisco networking concepts. Students are first introduced to theory-based concepts, which are followed-up with practical hands-on labs. This book is suitable for use in any Cisco networking course.', 'Hardbound', 'Course Technology', '2009', 'Networking', '70.0000'),
('1418842982', 'Microsoft Office Access 2003, Illustrated Introductory, CourseCard Edition 1st edition', 'Lisa Friedrichsen', 'Part of the Illustrated series, this text offers a visual, flexible way to build Microsoft Access 2003 skills.', 'Softbound', 'Course Technology', '2006', 'Databases', '35.0000'),
('1418843628', 'Microsoft Office Access 2003: Complete Concepts and Techniques, CourseCard Edition 2nd edition', 'Gary B. Shelly, Thomas J. Cashman,', 'For the past three decades, the Shelly Cashman Series® has effectively introduced computers to millions of students – consistently providing the highest quality, most up-to-date, and innovative materials in computer education. We are proud of the fact that our series of Microsoft Office 4.3, Microsoft Office 95, Microsoft Office 97, Microsoft Office 2000, and Microsoft Office XP textbooks have been the most widely used books in computer education. With each new edition of our Office books, we have made significant improvements based on software changes and comments made by both instructors and students. Our Microsoft Office 2003 books continue with the innovation, quality, and reliability that you have come to expect from the Shelly Cashman Series.', 'Softbound', 'Course Technology', '2006', 'Databases', '62.0000'),
('1418860115', 'Macromedia Flash 8 Interactive Movie Tutorials, Starter 1e', 'Jim Shuman', 'Add a new dimension to teaching Macromedia Flash 8 with this Cool School interactus movie tutorial CD!', 'Softbound', 'Course Technology', '2007', 'Game Design', '40.0000'),
('1439079285', 'Adobe Photoshop CS4 (Introductory Concepts and Techniques) 1st edition', 'Gary B. Shelly & Joy L. Starks', 'Part of the highly successful Shelly Cashman series, ADOBE® PHOTOSHOP® CS4: COMPREHENSIVE CONCEPTS AND TECHNIQUES follows the proven Shelly Cashman step-by-step, screen-by-screen approach to learning the Photoshop CS4 software. In this text, you will find features designed to engaged students, improve retention, and prepare them for future success. Students are encouraged to expand their understanding of the Photoshop CS4 software and graphic design concepts through experimentation, exploration and planning ahead. Brand new end of chapter exercises prepare students to become more capable software users by requiring them to use critical-thinking and problem-solving skills.', 'Softbound without CD', 'Course Technology', '2010', 'Web Design', '36.0000'),
('1584502428', 'Learning Visual Basic.NET Through Applications 1st edition', 'Clayton Crooks II', 'This book/CD-ROM package explores a different approach to learning Visual Basic.net thanmost programming books on the market. Instead of reading chapter after chapter on a single topic, Learning Visual Basic.net through Applications focuses on having the reader complete a project in each chapter. The reader learns to create practical applications that he can actually use, such as an image browser, an email checker, an MP3 player, games, and much more. Each chapter is self-contained, allowing the reader to "skip" to the project of specific interest. Learning Visual Basic.net through Applications is simply the easiest way for programmers to learn Visual Basic.net.\r\n\r\nFeatures', 'Softbound with CD', 'Delmar Learning', '2002', 'Programming', '55.0000'),
('1584503955', 'Game Art (Creation, Direction, and Careers) 1st edition', 'Riccard Linde', 'Game Art: Creation, Direction, and Careers is written to give 3D artists who want to move into the games industry the tools and techniques they need to be successful. It is also written for practicing game artists looking to increase their knowledge and skills so they can advance to the next level. As the gap between GFX programmers and artists continues to grow, it is more important than ever for artists to understand how and why art works in games. This doesn''t mean you have to become a programmer, but if you can understand the terminology and know why the technical details of your art are so important, you''ll have the skills every studio wants. This book teaches you these skills. The first two parts define the artistic process involved in creating game art, including the basic knowledge and skills you need to solve common problems artists face. The last two parts cover technical performance information and the more advanced techniques for game art creation. Due to the similar workflows in today''s 3D packages and the many in-house programs used in game development, the book teaches game-industry methods from a non-program specific perspective. The book does assume a working knowledge of at least one major 3D program (3ds max® or Maya®) and Photoshop®.', 'Softbound without CD', 'Delmar Learning', '2005', 'Game Art', '52.0000'),
('1584504498', 'Introduction To UNIX/Linux 1st edition', 'Christopher Diaz', 'The UNIX system has steadily gained in popularity over the years. Many businesses and educational institutions as well as individuals have begun using UNIX/Linux because of its power, stability, reliability, and flexibility. With this increase in users, as well as potential users, comes the strong need for a complete and comprehensive text that will easily guide Windows users in the conversion to UNIX. Introduction to UNIX provides the necessary background and knowledge to become familiar with the UNIX/Linux environment and understand how to use its potential. For educational institutions, the book is designed to present a broad and thorough UNIX background for courses taken by students in computer, business, engineering, mathematics, education, and other majors. The book is also intended to assist the individual who wishes to learn UNIX independently by supplying them with all of the basic information on how to use UNIX and its functions. Anyone with any version of UNIX will find this book helpful as many of the concepts covered are universal and apply to all UNIX/Linux systems. The book explores many significant topics including creating and editing files as well as generating and developing professional-looking typeset documents. In addition, the book also covers programming related topics such as writing code to process files and provide a convenient way for users to accomplish tasks and how to build, run, debug, measure, and analyze performance of C++ programs. Written in an easy-to-follow manner, Introduction to UNIX is the essential guide for the student looking to learn more about the UNIX system or the individual who wants to make the transition to UNIX.', 'Softbound', 'Delmar Learning', '2006', 'Programming', '55.0000'),
('1584504668', 'Creating Content Management Systems in Java 1st edition', 'Arron Ferguson', 'In today''s fast-paced, information-packed world, it''s critical for businesses to organize and manipulate the data gathered from customers, sales, and product responses, etc. into usable information. Content Management Systems (CMS) can do this for your business easily and efficiently. There are several commercial systems available, but customizing one for your specific needs is usually necessary based on your data. Creating Content Management Systems in Java teaches you how to develop an open source CMS from scratch using XML as the storage mechanism, XSLT as the presentation layer, and Java and JSPs & Servlets to realize the multi-tiered architecture. The book also covers data modeling in XML and the use of XSLT as a presentation vehicle for custom XML formats. Creating Content Management Systems in Java is written for Web and software developers (specifically Java developers) who wish to learn more about the field of content management. The book provides a practical, applied perspective with complete demonstrations using code to show you how a solution or feature can be implemented. Throughout the book you will work through the development of a complete, open source, working CMS example, beginning with the conceptual ideas of content management. From there you''ll dive into the exploration of practical design solutions, and then move into the final implementations in each tier of the software that becomes the CMS. To benefit the most from this book, you should already know the Java programming language and have a basic understanding of the Web. You do not need to know XML, XSLT, CSS, or XHTML because these topics are covered thoroughly, although a basic understanding will be helpful. So, if you need to learn more about CMS development, this is the book for you.', 'Softbound', 'Delmar Learning', '2007', 'Programming', '51.0000'),
('1584504838', 'Macromedia Flash Professional 8 Game Graphics 1st edition', 'Robert Firebaugh', 'Creating graphics for Flash games can be fun and rewarding, especially when you can channel your imagination into your art and provide potential players with a fun entertainment experience. Written for anyone creating games with Flash, Macromedia® Flash(TM) Professional 8 Game Graphics teaches the essentials of Flash game art. You''ll learn all about what Flash graphics are, how to create your own, and how to import them into working game source files. The book covers vector and raster graphics and explains how both can be used to improve the performance of your game. Helpful tips and techniques are included throughout to help you become more efficient at creating user interfaces, game character sprites, and special effects. And several real-world game examples are used to teach about the development process for creating game graphics and preparing them correctly for a smooth transition to programming. You don''t have to be an artist to use this book, because the graphic techniques taught don''t require a painter''s hand. So if you want to create awesome graphics for your Flash games, this is the place to get started.', 'Softbound', 'Delmar Learning,', '2007', 'Game Art', '55.0000'),
('1584505486', 'Creating Game Art for 3D Engines 1e', 'Brad Strong', 'Learn how to create commercial-quality game art and make it come alive in a 3D engine! "Creating Game Art for 3D Engines" is the ideal guide for the serious student or aspiring animator who wants to learn how to create and successfully export game art, from simple shapes to full-blown characters. Using Autodesk® 3ds Max® to generate models and animations, and Torque as the 3D game engine, the book provides step-by-step instructions on how to model, unwrap, texture, rig, export, and script all of the essential art assets required for a game. Unlike other books that cover only art creation, Creating Game Art for 3D Engines teaches you how to create art specifically with the game engine in mind. All of the principles and techniques are universal and can be applied to any 3D software or game engine. Get ready to make your game ideas a reality!', 'Softbound', 'Delmar Learning', '2008', 'Game Art', '50.0000'),
('1584505591', 'Ultimate Game Programming with DirectX 2nd edition', 'Allen Sherrod', 'Make your own games using DirectX 10 and C++ with Ultimate\r\nGame Programming with DirectX, Second Edition. Written for\r\nexperienced programmers who want to learn DirectX 10 and\r\nhow to apply it to game creation, this book goes in-depth with\r\nDirectX 10 and each of its subsystems. Every part of the gamedevelopment\r\nprocess is covered and you’ll apply your existing\r\ngame-development skills to the new techniques and tools\r\ncovered in the book. Beginning with an introduction to DirectX\r\nand Direct3D, you’ll work your way through graphical interfaces,\r\nanimation paths,advanced lighting and shadows,various surfacemapping\r\ntechniques, and even sound. One topic is covered\r\nper chapter and end-of-chapter questions help you practice\r\nand reinforce your new skills.Whether you’re a current gamedevelopment\r\nstudent or a professional developer, you’ll find\r\nthe information and techniques you need to gain a clear understanding\r\nof game programming with DirectX 10.', 'Softbound without CD', 'Delmar Learning', '2009', 'Game Programming', '65.0000'),
('1598633600', 'Beginning C++ Through Game Programming 2e', 'Michael Dawson', 'Beginning C++ Through Game Programming, Second Edition approaches C++ from a game programming perspective unlike any other on the market. Offering a thorough and modern introduction to C++, this book is everything that an aspiring game programmer needs in order to learn the fundamentals of C++ and game programming basics. There is no programming experience necessary. You''ll begin within the fundamental steps of C++ and game programming. The book presents a small, but complete program for each new concept and a complete game program at the end of each chapter. At the end of the book, you''ll create a final game project that combines most of the major topics you''ve just covered. Skillfully written in an easy-to-understand manner, this is a great place to get started with game programming.', 'Softbound with CD', 'Delmar Learning', '2007', 'Game Programming', '35.0000'),
('1598633988', 'Beginning Game Programming with Flash 1st edition', 'Hamsa Suri, \r\nLakshmi Prayaga', 'If you are new to game programming and want to learn how to create dynamic, robust, and fun 2D games, "Beginning Game Programming with Flash" is the book for you! Written for introductory game programming students and other enthusiasts, the book begins with an overview of the Flash graphical user interface (GUI), explaining the four main components of the Flash authoring environment: the stage, timeline, tools and panels, and symbols. Once you are comfortable working with the GUI, you’ll dive into using ActionScript, the language used to write code in Flash, which controls the graphics, sound files, and interactivity between the player and the game assets. As you work through the book you’ll discover how to create a storyboard for a game, add animation and visual effects, insert movie clips and sound files, apply math and physics concepts to make game objects move, and develop and test a Flash game. Easy-to-follow, step-by-step instructions walk you through each step of the game-building process, and end-of-chapter exercises, tutorials, and games-based projects help you reinforce and apply the concepts you have learned. "Beginning Game Programming with Flash" covers all the essential elements of game programming, making it a comprehensive and fun guide for beginning game programmers.', 'Sotfbound without CD', 'Delmar Learning', '2008', 'Game Programming', '35.0000'),
('1598634763', 'Beginning Java Game Programming 2nd edition', 'Jonathan S. Harbour', 'Are you serious about learning how to create real, Java-based games for fun and sharing? Do you have a basic understanding of the Java programming language? If you’ve answered yes, then you are ready to get started building web-based 2D games from scratch using the latest version of the Java Development Kit! "Beginning Java Game Programming, Second Edition" is a hands-on guide that is perfect for beginner-level game programmers who want to quickly and easily learn how to create games using Java. Written in simple language, the book teaches each new skill using engaging tutorials, followed by end-of-chapter questions and exercises to help reinforce what you’ve just learned. Each chapter builds upon the previous ones, allowing you to repeat and practice the techniques covered. You’ll begin with the basics of writing a simple 2D game using vector graphics, move on to utilizing Java’s advanced 2D library to add animation and sound effects, and end by creating a professional, sprite-based game full of interesting artwork and details that you can share with others on your own website!', 'Softbound without CD', 'Delmar Learning', '2008', 'Game Programming', '35.0000'),
('159863528X', 'Beginning OpenGL Game Programming 2nd edition', 'Luke Benstead', 'Are you a beginning programmer just getting started in 3D graphics programming? If you’re comfortable\r\nprogramming in C++ and have a basic understanding of 3D math concepts, Beginning OpenGL\r\nGame Programming, Second Edition will get you started programming 3D graphics for games\r\nusing the OpenGL API. Revised to work with the latest version of OpenGL, OpenGL 3.0, this book is\r\nperfect for programmers who are new to game development or new to OpenGL. New skills and concepts\r\nare taught using step-by-step instructions, with end-of-chapter exercises for testing and reinforcement.\r\nFrom creating a simple OpenGL application, to applying texture mapping, and even displaying 2D fonts,\r\nyou’ll find complete yet concise coverage of all the newest features of OpenGL as they apply to 3D\r\ngraphics for game development. And by the end of the book, you’ll be able to apply your newfound\r\nknowledge of OpenGL to create your very own games.', 'Softbound without CD', 'Delmar Learning,', '2010', 'Game Programming', '40.0000'),
('1844808777', '3D Games Programming  Using DirectX 10 and Open GL 1st edition', 'Pierre Rautenbach', '3D Game Programming focuses on all the elements making up a 3-D first-person shooter game engine using a bottom-up approach. By following the easy-to-read text, the reader will learn how to create his or her own next-generation 3-D game engine with support for vertex and pixel shading GPU techniques (via Cg and HLSL), dynamic lighting and shadowing (via stencil shadow volumes), geometric meshes, audio, artificial intelligence, physics, environmental reflections, refraction and advanced lighting techniques such as High Dynamic Range lighting.\r\n\r\nDealing with the cross-platform programming of 3-D Games for both Linux/MacOS X (via OpenGL/GLUT) and Windows (via DirectX 10 or OpenGL/GLUT) platforms, this book bridges an existent rift in the game development community. In addition to covering these APIs in-depth, the reader is also introduced to other game programming topics such as game development techniques and methodologies, particle systems, shader-based special effects, physics-based animation and artificial intelligence, making this the most comprehensive game programming guide around.', 'Softbound with CD', 'Cengage Learning EMEA', '2009', NULL, '50.0000'),
('1931841624', 'Learn SQL In a Weekend 1e', 'Deanna Dicken, \r\nKevin Thompson', 'With this book as your guide, you can progress from basic database design to the more advanced techniques of database communication in just one weekend. On Friday evening, start with the basics of SQL as you set up a sample database. On Saturday, practice database communications as you cover queries, the SELECT command, and relational database creation. Pull it all together on Sunday with optimization techniques and security triggers. End the weekend with a practical look at how programmers use SQL to make their jobs easier and how popular programming languages can access your database.', 'Softbound', 'Delmar Learning', '2002', 'Databases', '48.0000'),
('2002102792', 'Sams Teach Yourself Viual Studio.Net in 21 Days', 'Jason Beres', 'Sams Teach Yourself Visual Studio .NET in 21 Days will help developers that are new to application development and experienced developers understand how to use the .NET Framework and Visual Studio .NET to rapidly develop any type of computer application. The Visual Studio .NET development environment is the most comprehensive developer tool ever created, putting that together with the .NET Frameworks'' Class Libraries, the developer has everything he or she needs to get up-to-speed on Microsoft''s latest revolution in application development. This book will guide the developer through using the VS .NET IDE, the Visual Basic .NET and C# language, and the supporting tools available from Microsoft to create Windows and Web-based applications. The market is full of books that pretty much say the same thing, which is already available in the help files, the author of this book has written and deployed over a dozen successful applications using Visual Studio .NET and the .NET Framework. All of his expertise and experience is used to give you the most comprehensive title on using Visual Studio .NET.', 'Soft bound, Glossy paper, with CD', 'Sams Publishing', '2003', 'ICT', '40.0000'),
('2002106457', 'Sams Teach Yourself Java 2 in 24 Hours', 'Rogers Cadenhead', 'Sams Teach Yourself Java in 24 Hours is a step-by-step tutorial that teaches someone with no previous programming experience how to create simple Java programs and applets.\r\n\r\nIt starts out at a lower level than Sams Teach Yourself Java in 21 Days, and takes things at a slower pace, focusing on key programming concepts and essential Java basics.\r\n\r\nAlthough the basic structure of the book, and many of its examples, will remain the same in this new edition, the author will make use of dozens of reader comments to make improvements to explanatory text and example programs.\r\n\r\nThis new edition of the book maintains and improves upon all these qualities, while updating, revising, and reorganizing the material to cover the latest developments in Java and to expand the book''s coverage of core Java programming topics.', 'Soft bound, Glossy Paper', 'Sams Publishing', '2003', 'ICT', '250.0000'),
('1234', 'Hello world', 'gimo', 'for world peach', 'for the childres', 'ako', '2017', 'community', '0.0000'),
('1233', 'Hello world', 'gimo', 'for world peach', 'for the childres', 'ako', '2017', 'community', '0.0000'),
('1235', 'Hello world', 'gimo', 'for world peach', 'for the childres', 'ako', '2017', 'community', '0.0000'),
('1979', 'MVC', 'Gilmore Baldevarona', 'This is a tutorial for dummy using PHP MVC.', 'Tutorial', 'MSCS', '2017', 'Web', '1000.0000'),
('', 'sample mvv', 'gimo', 'asdfasdfasdfadfafasdfasdfasdfasdfadfasdfadfasssssssssssssssssssssssssssssssssfafasfafasfa', 'adf', 'asd', 'asdf', 'asdf', '33.0000'),
('123', 'good morning', 'gilmore', 'asdfgfhfhgjghjgjncvbcvbc', 'aqqqqqqqq', 'a', 's', 's', '33.0000');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tblbooks`
--
ALTER TABLE `tblbooks`
 ADD PRIMARY KEY (`ISBN`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
